### ISSUE TITLE
Google Play?

### ISSUE THREAD

**Issue by friedolatzger** [ZorgeR/Noizer#1]
Hi,
is your app available on [Google Play](https://play.google.com/store/apps) and/or [F-Droid](https://f-droid.org/)? If yes, can you please put a link to it in the README? Thank you so much!

**Comment by ZorgeR** [comment]
Hello!
Fixed, Google Play link added. Sorry but no F-Droid link, we has send request for added to F-Droid repo, but it's not approved.
