### ISSUE TITLE
проблема с Asus ZenFone 2 Laser ZE550KL

### ISSUE THREAD

**Issue by anonymous71** [ZorgeR/Noizer#1]
Если запустит какой-то эффект и телефон перейдёт в другую ориентацию, то звук идёт, а в статусе написано выкл. Перевод обратно в первоначальную ориентацию не помогает. Asus ZenFone 2 Laser ZE550KL , 720p, Android 6.0.1

**Comment by ZorgeR** [comment]
fixed in : https://github.com/ZorgeR/Noizer/commit/a2045affe7e21c26c3050a88519f23ef04c4a3bc
